/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventStudioRouteImport } from './routes/event-studio'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as EventVisionIdRouteImport } from './routes/event-vision.$id'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as OurWorkIndexRouteImport } from './routes/our-work.index'
import { Route as OurWorkSlugRouteImport } from './routes/our-work.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventStudioRoute = EventStudioRouteImport.update({
  id: '/event-studio',
  path: '/event-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/destinations/$slug',
  path: '/destinations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventVisionIdRoute = EventVisionIdRouteImport.update({
  id: '/event-vision/$id',
  path: '/event-vision/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OurWorkIndexRoute = OurWorkIndexRouteImport.update({
  id: '/our-work/',
  path: '/our-work/',
  getParentRoute: () => rootRouteImport,
} as any)
const OurWorkSlugRoute = OurWorkSlugRouteImport.update({
  id: '/our-work/$slug',
  path: '/our-work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/event-studio': typeof EventStudioRoute
  '/services': typeof ServicesRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/event-vision/$id': typeof EventVisionIdRoute
  '/events/$slug': typeof EventsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/our-work/$slug': typeof OurWorkSlugRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/our-work/': typeof OurWorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/event-studio': typeof EventStudioRoute
  '/services': typeof ServicesRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/event-vision/$id': typeof EventVisionIdRoute
  '/events/$slug': typeof EventsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/our-work/$slug': typeof OurWorkSlugRoute
  '/destinations': typeof DestinationsIndexRoute
  '/events': typeof EventsIndexRoute
  '/journal': typeof JournalIndexRoute
  '/our-work': typeof OurWorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/event-studio': typeof EventStudioRoute
  '/services': typeof ServicesRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/event-vision/$id': typeof EventVisionIdRoute
  '/events/$slug': typeof EventsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/our-work/$slug': typeof OurWorkSlugRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/our-work/': typeof OurWorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/event-studio'
    | '/services'
    | '/destinations/$slug'
    | '/event-vision/$id'
    | '/events/$slug'
    | '/journal/$slug'
    | '/our-work/$slug'
    | '/destinations/'
    | '/events/'
    | '/journal/'
    | '/our-work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/event-studio'
    | '/services'
    | '/destinations/$slug'
    | '/event-vision/$id'
    | '/events/$slug'
    | '/journal/$slug'
    | '/our-work/$slug'
    | '/destinations'
    | '/events'
    | '/journal'
    | '/our-work'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/event-studio'
    | '/services'
    | '/destinations/$slug'
    | '/event-vision/$id'
    | '/events/$slug'
    | '/journal/$slug'
    | '/our-work/$slug'
    | '/destinations/'
    | '/events/'
    | '/journal/'
    | '/our-work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EventStudioRoute: typeof EventStudioRoute
  ServicesRoute: typeof ServicesRoute
  DestinationsSlugRoute: typeof DestinationsSlugRoute
  EventVisionIdRoute: typeof EventVisionIdRoute
  EventsSlugRoute: typeof EventsSlugRoute
  JournalSlugRoute: typeof JournalSlugRoute
  OurWorkSlugRoute: typeof OurWorkSlugRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
  OurWorkIndexRoute: typeof OurWorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-studio': {
      id: '/event-studio'
      path: '/event-studio'
      fullPath: '/event-studio'
      preLoaderRoute: typeof EventStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/destinations/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-vision/$id': {
      id: '/event-vision/$id'
      path: '/event-vision/$id'
      fullPath: '/event-vision/$id'
      preLoaderRoute: typeof EventVisionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-work/': {
      id: '/our-work/'
      path: '/our-work'
      fullPath: '/our-work/'
      preLoaderRoute: typeof OurWorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-work/$slug': {
      id: '/our-work/$slug'
      path: '/our-work/$slug'
      fullPath: '/our-work/$slug'
      preLoaderRoute: typeof OurWorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EventStudioRoute: EventStudioRoute,
  ServicesRoute: ServicesRoute,
  DestinationsSlugRoute: DestinationsSlugRoute,
  EventVisionIdRoute: EventVisionIdRoute,
  EventsSlugRoute: EventsSlugRoute,
  JournalSlugRoute: JournalSlugRoute,
  OurWorkSlugRoute: OurWorkSlugRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
  OurWorkIndexRoute: OurWorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
